from enum import Enum


class DatabaseOperation(Enum):
    INSERT = "INSERT"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    SELECT = "SELECT"
    TRANSACTION_COMMIT = "TRANSACTION_COMMIT"
    TRANSACTION_ROLLBACK = "TRANSACTION_ROLLBACK"
